board_manager:
  additional_urls:
    - https://espressif.github.io/arduino-esp32/package_esp32_index.json
directories:
  data: C:\Projects\esp32Remote\esp32-leonardo-hid-bridge\.arduino-data
  downloads: C:\Projects\esp32Remote\esp32-leonardo-hid-bridge\.arduino-data\staging
  user: C:\Projects\esp32Remote\esp32-leonardo-hid-bridge\.arduino-sketchbook
